### PR TITLE
Add pathogen instructions and link

### PR DESCRIPTION
**Pull request by LiNk-NY**
Hi Jakson, @jalvesaq 
I hope you are well. 
It would be useful to have instructions for pathogen users in the `README.md`. 
Best regards,
Marcel

### CODE REVIEW

**Comment by jalvesaq** [comment]
What are the advantages of pathogen over vim-plug?

**Comment by LiNk-NY** [comment]
I don't know much about `vim-plug` so I can't comment about it but
for pathogen users, it is quite easy to use and it would be nice to 
have some instructions there. 

Thanks for your useful plugin.

**Comment by jalvesaq** [comment]
Searching "vim-plug vs pathogen" I could find mostly advantages of vim-plug over pathogen. Indeed, I've used another plugin manager in the past (I don't remember if it was pathogen) but switched to vim-plug because it's simpler, yet more powerful. So, I'm sorry, but I'm still not convinced that I should merge your pull request.

**Comment by LiNk-NY** [comment]
Hi Jakson, @jalvesaq 
Thanks for following up. That is fair. I don't manage a lot of plugins so I find it easy to use. 
Perhaps this feedback might help. https://vi.stackexchange.com/a/390
Feel free to close the PR. 
Best regards,
Marcel

**Comment by jalvesaq** [comment]
Thank you!

**Pull request closed without merging**
