### PR TITLE
Fix bugs regarding the use of vim variables

### PR DESCRIPTION
**Pull request by NobodyXu**
This pr:

 1. Fix bugs regarding the use of vim variables;
 2.  Add `.gitignore` for `python3`;
 3. Remove `ftplugin/__pycache`

for issue #60.

### CODE REVIEW

**Comment by NobodyXu** [comment]
It seems that I had slipped a bug into the code.

I found this bug before and I thought I have fixed it.

**Comment by jalvesaq** [comment]
I can't merge this pull request. Github says: "This branch has conflicts that must be resolved".

**Comment by NobodyXu** [comment]
The problem is on the 64th to 68th line:

```
<<<<<<< pylines
        call VimCmdLineSendCmd("sys.path.append('" . s:path . "')")
=======
        call VimCmdLineSendCmd("sys.path.append('" . path . "')")
>>>>>>> pylines
```

`path` is defined on line 53 as a package-wide variable:

```
    let s:path = expand('<sfile>:p:h')
```

In the previously merge code, I used `path` on the 65th line, which is a mistake that cause `vim` to emit errors when sending file.

The right way is to use `s:path`, which is why I opened this pr.

So I think the right way to resolve this conflict is to remove the original code on the 64th line.

**Comment by jalvesaq** [comment]
I'm sorry, but I don't know how to solve pull request conflicts... You have to do a pull request that can be merged into the pylines branch, so I will just press the "Squash and merge" button.

**Comment by jalvesaq** [comment]
The conflict is not fixed. I can't help you because I'm really not good using git. So, I would try:

- Delete the NobodyXu:pylines branch.
- Clone jalvesaq:pylines branch again.
- Make the changes again.
- Do a new pull request.

**Comment by NobodyXu** [comment]
Thank you, @jalvesaq , it works!

I have now submitted a new pull request #64 .

**Pull request closed without merging**
